// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-tzZrWAcGGRNDV9UUjfytojaYR_VV_M',
    appId: '1:774339197182:web:d76d084a6c61d11097cdaf',
    messagingSenderId: '774339197182',
    projectId: 'parkit-e05f6',
    authDomain: 'parkit-e05f6.firebaseapp.com',
    storageBucket: 'parkit-e05f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByGMEl4UBScDfdndjpMpIs8n44KL0D8OY',
    appId: '1:774339197182:android:13ed225ace75063697cdaf',
    messagingSenderId: '774339197182',
    projectId: 'parkit-e05f6',
    storageBucket: 'parkit-e05f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vwCFMdlnSM8gWk8AQ0nuRlyF0clTTJk',
    appId: '1:774339197182:ios:6d13b457ed9011a397cdaf',
    messagingSenderId: '774339197182',
    projectId: 'parkit-e05f6',
    storageBucket: 'parkit-e05f6.appspot.com',
    iosClientId: '774339197182-340i5fbr2dbqiu8boom07c3jn0316jdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.internTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vwCFMdlnSM8gWk8AQ0nuRlyF0clTTJk',
    appId: '1:774339197182:ios:6d13b457ed9011a397cdaf',
    messagingSenderId: '774339197182',
    projectId: 'parkit-e05f6',
    storageBucket: 'parkit-e05f6.appspot.com',
    iosClientId: '774339197182-340i5fbr2dbqiu8boom07c3jn0316jdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.internTask',
  );
}
